use_frameworks!

target 'HDTabbedPageView_Example' do
  pod 'HDTabbedPageView', :path => '../'

  target 'HDTabbedPageView_Tests' do
    pod 'HDTabbedPageView', :path => '../'
    pod 'Quick', '~> 1.2.0'
  end
end
